services:

  app:
    build: .
    container_name: rag_app
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis-db
    ports:
      - "6379:6379"  # The database port
      - "8001:8001"  # RedisInsight (The UI)
    environment:
      - REDIS_ARGS=--maxmemory 512mb --maxmemory-policy volatile-lru